# Generated by Django 3.2 on 2021-05-11 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
